#!/bin/sh /etc/rc.common
# procd init script for the MistUI daemon.

USE_PROCD=1
START=95
STOP=10

PROG=/usr/bin/mistd
DB=/etc/mistui/mistui.db
ADDR=127.0.0.1:8080

start_service() {
	[ -d /etc/mistui ] || mkdir -p /etc/mistui
	procd_open_instance
	procd_set_param command "$PROG" -addr "$ADDR" -db "$DB"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
